/*
 * This file is generated by jOOQ.
 */
package ru.itis.jooq.`_`.enums


import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema

import ru.itis.jooq.Public


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
enum class ObjectStatus(@get:JvmName("literal") public val literal: String) : EnumType {
    NEW("NEW"),
    SUCCESS("SUCCESS"),
    ERROR("ERROR"),
    `NOT FOUND`("NOT FOUND");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getName(): String = "object_status"
    override fun getLiteral(): String = literal
}
