/*
 * This file is generated by jOOQ.
 */
package ru.itis.jooq.`_`.tables.references




/**
 * The table <code>public.area</code>.
 */
val AREA: ru.itis.jooq.`_`.tables.Area = ru.itis.jooq.`_`.tables.Area.AREA

/**
 * The table <code>public.object</code>.
 */
val OBJECT: ru.itis.jooq.`_`.tables.Object = ru.itis.jooq.`_`.tables.Object.OBJECT

/**
 * The table <code>public.quarter</code>.
 */
val QUARTER: ru.itis.jooq.`_`.tables.Quarter = ru.itis.jooq.`_`.tables.Quarter.QUARTER

/**
 * The table <code>public.region</code>.
 */
val REGION: ru.itis.jooq.`_`.tables.Region = ru.itis.jooq.`_`.tables.Region.REGION
