/*
 * This file is generated by jOOQ.
 */
package ru.itis.jooq.`_`.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AreaRecord() : UpdatableRecordImpl<AreaRecord>(ru.itis.jooq.`_`.tables.Area.AREA) {

    open var code: Short?
        set(value): Unit = set(0, value)
        get(): Short? = get(0) as Short?

    open var regionCode: Short?
        set(value): Unit = set(1, value)
        get(): Short? = get(1) as Short?

    open var name: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var description: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Short?> = super.key() as Record1<Short?>

    /**
     * Create a detached, initialised AreaRecord
     */
    constructor(code: Short? = null, regionCode: Short? = null, name: String? = null, description: String? = null): this() {
        this.code = code
        this.regionCode = regionCode
        this.name = name
        this.description = description
        resetChangedOnNotNull()
    }
}
