/*
 * This file is generated by jOOQ.
 */
package ru.itis.jooq.`_`.tables.records


import java.math.BigDecimal
import java.time.LocalDate

import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ObjectRecord() : UpdatableRecordImpl<ObjectRecord>(ru.itis.jooq.`_`.tables.Object.OBJECT) {

    open var code: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var quarterCode: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var loadStatus: ru.itis.jooq.`_`.enums.ObjectStatus?
        set(value): Unit = set(2, value)
        get(): ru.itis.jooq.`_`.enums.ObjectStatus? = get(2) as ru.itis.jooq.`_`.enums.ObjectStatus?

    open var updateDate: LocalDate?
        set(value): Unit = set(3, value)
        get(): LocalDate? = get(3) as LocalDate?

    open var `data`: JSONB?
        set(value): Unit = set(4, value)
        get(): JSONB? = get(4) as JSONB?

    open var area: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var costValue: BigDecimal?
        set(value): Unit = set(6, value)
        get(): BigDecimal? = get(6) as BigDecimal?

    open var permittedUseEstablishedByDocument: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var rightType: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var status: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    open var landRecordType: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    open var landRecordSubtype: String?
        set(value): Unit = set(11, value)
        get(): String? = get(11) as String?

    open var landRecordCategoryType: String?
        set(value): Unit = set(12, value)
        get(): String? = get(12) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised ObjectRecord
     */
    constructor(code: Int? = null, quarterCode: Int? = null, loadStatus: ru.itis.jooq.`_`.enums.ObjectStatus? = null, updateDate: LocalDate? = null, `data`: JSONB? = null, area: Int? = null, costValue: BigDecimal? = null, permittedUseEstablishedByDocument: String? = null, rightType: String? = null, status: String? = null, landRecordType: String? = null, landRecordSubtype: String? = null, landRecordCategoryType: String? = null): this() {
        this.code = code
        this.quarterCode = quarterCode
        this.loadStatus = loadStatus
        this.updateDate = updateDate
        this.`data` = `data`
        this.area = area
        this.costValue = costValue
        this.permittedUseEstablishedByDocument = permittedUseEstablishedByDocument
        this.rightType = rightType
        this.status = status
        this.landRecordType = landRecordType
        this.landRecordSubtype = landRecordSubtype
        this.landRecordCategoryType = landRecordCategoryType
        resetChangedOnNotNull()
    }
}
