/*
 * This file is generated by jOOQ.
 */
package ru.itis.jooq.`_`.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class QuarterRecord() : UpdatableRecordImpl<QuarterRecord>(ru.itis.jooq.`_`.tables.Quarter.QUARTER) {

    open var code: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var areaCode: Short?
        set(value): Unit = set(1, value)
        get(): Short? = get(1) as Short?

    open var name: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var description: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised QuarterRecord
     */
    constructor(code: Int? = null, areaCode: Short? = null, name: String? = null, description: String? = null): this() {
        this.code = code
        this.areaCode = areaCode
        this.name = name
        this.description = description
        resetChangedOnNotNull()
    }
}
