/*
 * This file is generated by jOOQ.
 */
package ru.itis.jooq.`_`.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class RegionRecord() : UpdatableRecordImpl<RegionRecord>(ru.itis.jooq.`_`.tables.Region.REGION) {

    open var code: Short?
        set(value): Unit = set(0, value)
        get(): Short? = get(0) as Short?

    open var name: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Short?> = super.key() as Record1<Short?>

    /**
     * Create a detached, initialised RegionRecord
     */
    constructor(code: Short? = null, name: String? = null): this() {
        this.code = code
        this.name = name
        resetChangedOnNotNull()
    }
}
