/*
 * This file is generated by jOOQ.
 */
package ru.itis.jooq.`_`.keys


import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val AREA_PKEY: UniqueKey<ru.itis.jooq.`_`.tables.records.AreaRecord> = Internal.createUniqueKey(ru.itis.jooq.`_`.tables.Area.AREA, DSL.name("area_pkey"), arrayOf(ru.itis.jooq.`_`.tables.Area.AREA.CODE), true)
val OBJECT_PKEY: UniqueKey<ru.itis.jooq.`_`.tables.records.ObjectRecord> = Internal.createUniqueKey(ru.itis.jooq.`_`.tables.Object.OBJECT, DSL.name("object_pkey"), arrayOf(ru.itis.jooq.`_`.tables.Object.OBJECT.CODE), true)
val QUARTER_PKEY: UniqueKey<ru.itis.jooq.`_`.tables.records.QuarterRecord> = Internal.createUniqueKey(ru.itis.jooq.`_`.tables.Quarter.QUARTER, DSL.name("quarter_pkey"), arrayOf(ru.itis.jooq.`_`.tables.Quarter.QUARTER.CODE), true)
val REGION_PKEY: UniqueKey<ru.itis.jooq.`_`.tables.records.RegionRecord> = Internal.createUniqueKey(ru.itis.jooq.`_`.tables.Region.REGION, DSL.name("region_pkey"), arrayOf(ru.itis.jooq.`_`.tables.Region.REGION.CODE), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val AREA__AREA_REGION_CODE_FKEY: ForeignKey<ru.itis.jooq.`_`.tables.records.AreaRecord, ru.itis.jooq.`_`.tables.records.RegionRecord> = Internal.createForeignKey(ru.itis.jooq.`_`.tables.Area.AREA, DSL.name("area_region_code_fkey"), arrayOf(ru.itis.jooq.`_`.tables.Area.AREA.REGION_CODE), ru.itis.jooq.`_`.keys.REGION_PKEY, arrayOf(ru.itis.jooq.`_`.tables.Region.REGION.CODE), true)
val OBJECT__OBJECT_QUARTER_CODE_FKEY: ForeignKey<ru.itis.jooq.`_`.tables.records.ObjectRecord, ru.itis.jooq.`_`.tables.records.QuarterRecord> = Internal.createForeignKey(ru.itis.jooq.`_`.tables.Object.OBJECT, DSL.name("object_quarter_code_fkey"), arrayOf(ru.itis.jooq.`_`.tables.Object.OBJECT.QUARTER_CODE), ru.itis.jooq.`_`.keys.QUARTER_PKEY, arrayOf(ru.itis.jooq.`_`.tables.Quarter.QUARTER.CODE), true)
val QUARTER__QUARTER_AREA_CODE_FKEY: ForeignKey<ru.itis.jooq.`_`.tables.records.QuarterRecord, ru.itis.jooq.`_`.tables.records.AreaRecord> = Internal.createForeignKey(ru.itis.jooq.`_`.tables.Quarter.QUARTER, DSL.name("quarter_area_code_fkey"), arrayOf(ru.itis.jooq.`_`.tables.Quarter.QUARTER.AREA_CODE), ru.itis.jooq.`_`.keys.AREA_PKEY, arrayOf(ru.itis.jooq.`_`.tables.Area.AREA.CODE), true)
