/*
 * This file is generated by jOOQ.
 */
package ru.itis.jooq.`_`.tables


import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

import ru.itis.jooq.Public


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Area(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ru.itis.jooq.`_`.tables.records.AreaRecord>?,
    parentPath: InverseForeignKey<out Record, ru.itis.jooq.`_`.tables.records.AreaRecord>?,
    aliased: Table<ru.itis.jooq.`_`.tables.records.AreaRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ru.itis.jooq.`_`.tables.records.AreaRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.area</code>
         */
        val AREA: Area = Area()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ru.itis.jooq.`_`.tables.records.AreaRecord> = ru.itis.jooq.`_`.tables.records.AreaRecord::class.java

    /**
     * The column <code>public.area.code</code>.
     */
    val CODE: TableField<ru.itis.jooq.`_`.tables.records.AreaRecord, Short?> = createField(DSL.name("code"), SQLDataType.SMALLINT.nullable(false), this, "")

    /**
     * The column <code>public.area.region_code</code>.
     */
    val REGION_CODE: TableField<ru.itis.jooq.`_`.tables.records.AreaRecord, Short?> = createField(DSL.name("region_code"), SQLDataType.SMALLINT.nullable(false), this, "")

    /**
     * The column <code>public.area.name</code>.
     */
    val NAME: TableField<ru.itis.jooq.`_`.tables.records.AreaRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("''::character varying"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>public.area.description</code>.
     */
    val DESCRIPTION: TableField<ru.itis.jooq.`_`.tables.records.AreaRecord, String?> = createField(DSL.name("description"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("''::character varying"), SQLDataType.VARCHAR)), this, "")

    private constructor(alias: Name, aliased: Table<ru.itis.jooq.`_`.tables.records.AreaRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ru.itis.jooq.`_`.tables.records.AreaRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ru.itis.jooq.`_`.tables.records.AreaRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.area</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.area</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.area</code> table reference
     */
    constructor(): this(DSL.name("area"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ru.itis.jooq.`_`.tables.records.AreaRecord>?, parentPath: InverseForeignKey<out Record, ru.itis.jooq.`_`.tables.records.AreaRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, AREA, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class AreaPath : Area, Path<ru.itis.jooq.`_`.tables.records.AreaRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ru.itis.jooq.`_`.tables.records.AreaRecord>?, parentPath: InverseForeignKey<out Record, ru.itis.jooq.`_`.tables.records.AreaRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<ru.itis.jooq.`_`.tables.records.AreaRecord>): super(alias, aliased)
        override fun `as`(alias: String): AreaPath = AreaPath(DSL.name(alias), this)
        override fun `as`(alias: Name): AreaPath = AreaPath(alias, this)
        override fun `as`(alias: Table<*>): AreaPath = AreaPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<ru.itis.jooq.`_`.tables.records.AreaRecord> = ru.itis.jooq.`_`.keys.AREA_PKEY
    override fun getReferences(): List<ForeignKey<ru.itis.jooq.`_`.tables.records.AreaRecord, *>> = listOf(ru.itis.jooq.`_`.keys.AREA__AREA_REGION_CODE_FKEY)

    private lateinit var _region: ru.itis.jooq.`_`.tables.Region.RegionPath

    /**
     * Get the implicit join path to the <code>public.region</code> table.
     */
    fun region(): ru.itis.jooq.`_`.tables.Region.RegionPath {
        if (!this::_region.isInitialized)
            _region = ru.itis.jooq.`_`.tables.Region.RegionPath(this, ru.itis.jooq.`_`.keys.AREA__AREA_REGION_CODE_FKEY, null)

        return _region;
    }

    val region: ru.itis.jooq.`_`.tables.Region.RegionPath
        get(): ru.itis.jooq.`_`.tables.Region.RegionPath = region()

    private lateinit var _quarter: ru.itis.jooq.`_`.tables.Quarter.QuarterPath

    /**
     * Get the implicit to-many join path to the <code>public.quarter</code>
     * table
     */
    fun quarter(): ru.itis.jooq.`_`.tables.Quarter.QuarterPath {
        if (!this::_quarter.isInitialized)
            _quarter = ru.itis.jooq.`_`.tables.Quarter.QuarterPath(this, null, ru.itis.jooq.`_`.keys.QUARTER__QUARTER_AREA_CODE_FKEY.inverseKey)

        return _quarter;
    }

    val quarter: ru.itis.jooq.`_`.tables.Quarter.QuarterPath
        get(): ru.itis.jooq.`_`.tables.Quarter.QuarterPath = quarter()
    override fun `as`(alias: String): Area = Area(DSL.name(alias), this)
    override fun `as`(alias: Name): Area = Area(alias, this)
    override fun `as`(alias: Table<*>): Area = Area(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Area = Area(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Area = Area(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Area = Area(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Area = Area(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Area = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Area = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Area = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Area = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Area = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Area = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Area = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Area = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Area = where(DSL.notExists(select))
}
