/*
 * This file is generated by jOOQ.
 */
package ru.itis.jooq.`_`.tables


import java.math.BigDecimal
import java.time.LocalDate

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

import ru.itis.jooq.Public


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Object(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ru.itis.jooq.`_`.tables.records.ObjectRecord>?,
    parentPath: InverseForeignKey<out Record, ru.itis.jooq.`_`.tables.records.ObjectRecord>?,
    aliased: Table<ru.itis.jooq.`_`.tables.records.ObjectRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ru.itis.jooq.`_`.tables.records.ObjectRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.object</code>
         */
        val OBJECT: Object = Object()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ru.itis.jooq.`_`.tables.records.ObjectRecord> = ru.itis.jooq.`_`.tables.records.ObjectRecord::class.java

    /**
     * The column <code>public.object.code</code>.
     */
    val CODE: TableField<ru.itis.jooq.`_`.tables.records.ObjectRecord, Int?> = createField(DSL.name("code"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.object.quarter_code</code>.
     */
    val QUARTER_CODE: TableField<ru.itis.jooq.`_`.tables.records.ObjectRecord, Int?> = createField(DSL.name("quarter_code"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.object.load_status</code>.
     */
    val LOAD_STATUS: TableField<ru.itis.jooq.`_`.tables.records.ObjectRecord, ru.itis.jooq.`_`.enums.ObjectStatus?> = createField(DSL.name("load_status"), SQLDataType.VARCHAR.defaultValue(DSL.field(DSL.raw("'NEW'::object_status"), SQLDataType.VARCHAR)).asEnumDataType(ru.itis.jooq.`_`.enums.ObjectStatus::class.java), this, "")

    /**
     * The column <code>public.object.update_date</code>.
     */
    val UPDATE_DATE: TableField<ru.itis.jooq.`_`.tables.records.ObjectRecord, LocalDate?> = createField(DSL.name("update_date"), SQLDataType.LOCALDATE, this, "")

    /**
     * The column <code>public.object.data</code>.
     */
    val DATA: TableField<ru.itis.jooq.`_`.tables.records.ObjectRecord, JSONB?> = createField(DSL.name("data"), SQLDataType.JSONB, this, "")

    /**
     * The column <code>public.object.area</code>.
     */
    val AREA: TableField<ru.itis.jooq.`_`.tables.records.ObjectRecord, Int?> = createField(DSL.name("area"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.object.cost_value</code>.
     */
    val COST_VALUE: TableField<ru.itis.jooq.`_`.tables.records.ObjectRecord, BigDecimal?> = createField(DSL.name("cost_value"), SQLDataType.NUMERIC, this, "")

    /**
     * The column
     * <code>public.object.permitted_use_established_by_document</code>.
     */
    val PERMITTED_USE_ESTABLISHED_BY_DOCUMENT: TableField<ru.itis.jooq.`_`.tables.records.ObjectRecord, String?> = createField(DSL.name("permitted_use_established_by_document"), SQLDataType.VARCHAR(128), this, "")

    /**
     * The column <code>public.object.right_type</code>.
     */
    val RIGHT_TYPE: TableField<ru.itis.jooq.`_`.tables.records.ObjectRecord, String?> = createField(DSL.name("right_type"), SQLDataType.VARCHAR(128), this, "")

    /**
     * The column <code>public.object.status</code>.
     */
    val STATUS: TableField<ru.itis.jooq.`_`.tables.records.ObjectRecord, String?> = createField(DSL.name("status"), SQLDataType.VARCHAR(128), this, "")

    /**
     * The column <code>public.object.land_record_type</code>.
     */
    val LAND_RECORD_TYPE: TableField<ru.itis.jooq.`_`.tables.records.ObjectRecord, String?> = createField(DSL.name("land_record_type"), SQLDataType.VARCHAR(128), this, "")

    /**
     * The column <code>public.object.land_record_subtype</code>.
     */
    val LAND_RECORD_SUBTYPE: TableField<ru.itis.jooq.`_`.tables.records.ObjectRecord, String?> = createField(DSL.name("land_record_subtype"), SQLDataType.VARCHAR(128), this, "")

    /**
     * The column <code>public.object.land_record_category_type</code>.
     */
    val LAND_RECORD_CATEGORY_TYPE: TableField<ru.itis.jooq.`_`.tables.records.ObjectRecord, String?> = createField(DSL.name("land_record_category_type"), SQLDataType.VARCHAR(128), this, "")

    private constructor(alias: Name, aliased: Table<ru.itis.jooq.`_`.tables.records.ObjectRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ru.itis.jooq.`_`.tables.records.ObjectRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ru.itis.jooq.`_`.tables.records.ObjectRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.object</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.object</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.object</code> table reference
     */
    constructor(): this(DSL.name("object"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ru.itis.jooq.`_`.tables.records.ObjectRecord>?, parentPath: InverseForeignKey<out Record, ru.itis.jooq.`_`.tables.records.ObjectRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, OBJECT, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class ObjectPath : Object, Path<ru.itis.jooq.`_`.tables.records.ObjectRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ru.itis.jooq.`_`.tables.records.ObjectRecord>?, parentPath: InverseForeignKey<out Record, ru.itis.jooq.`_`.tables.records.ObjectRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<ru.itis.jooq.`_`.tables.records.ObjectRecord>): super(alias, aliased)
        override fun `as`(alias: String): ObjectPath = ObjectPath(DSL.name(alias), this)
        override fun `as`(alias: Name): ObjectPath = ObjectPath(alias, this)
        override fun `as`(alias: Table<*>): ObjectPath = ObjectPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<ru.itis.jooq.`_`.tables.records.ObjectRecord> = ru.itis.jooq.`_`.keys.OBJECT_PKEY
    override fun getReferences(): List<ForeignKey<ru.itis.jooq.`_`.tables.records.ObjectRecord, *>> = listOf(ru.itis.jooq.`_`.keys.OBJECT__OBJECT_QUARTER_CODE_FKEY)

    private lateinit var _quarter: ru.itis.jooq.`_`.tables.Quarter.QuarterPath

    /**
     * Get the implicit join path to the <code>public.quarter</code> table.
     */
    fun quarter(): ru.itis.jooq.`_`.tables.Quarter.QuarterPath {
        if (!this::_quarter.isInitialized)
            _quarter = ru.itis.jooq.`_`.tables.Quarter.QuarterPath(this, ru.itis.jooq.`_`.keys.OBJECT__OBJECT_QUARTER_CODE_FKEY, null)

        return _quarter;
    }

    val quarter: ru.itis.jooq.`_`.tables.Quarter.QuarterPath
        get(): ru.itis.jooq.`_`.tables.Quarter.QuarterPath = quarter()
    override fun `as`(alias: String): Object = Object(DSL.name(alias), this)
    override fun `as`(alias: Name): Object = Object(alias, this)
    override fun `as`(alias: Table<*>): Object = Object(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Object = Object(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Object = Object(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Object = Object(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Object = Object(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Object = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Object = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Object = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Object = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Object = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Object = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Object = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Object = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Object = where(DSL.notExists(select))
}
