/*
 * This file is generated by jOOQ.
 */
package ru.itis.jooq.`_`.tables


import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

import ru.itis.jooq.Public


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Region(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ru.itis.jooq.`_`.tables.records.RegionRecord>?,
    parentPath: InverseForeignKey<out Record, ru.itis.jooq.`_`.tables.records.RegionRecord>?,
    aliased: Table<ru.itis.jooq.`_`.tables.records.RegionRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ru.itis.jooq.`_`.tables.records.RegionRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.region</code>
         */
        val REGION: Region = Region()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ru.itis.jooq.`_`.tables.records.RegionRecord> = ru.itis.jooq.`_`.tables.records.RegionRecord::class.java

    /**
     * The column <code>public.region.code</code>.
     */
    val CODE: TableField<ru.itis.jooq.`_`.tables.records.RegionRecord, Short?> = createField(DSL.name("code"), SQLDataType.SMALLINT.nullable(false), this, "")

    /**
     * The column <code>public.region.name</code>.
     */
    val NAME: TableField<ru.itis.jooq.`_`.tables.records.RegionRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<ru.itis.jooq.`_`.tables.records.RegionRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ru.itis.jooq.`_`.tables.records.RegionRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ru.itis.jooq.`_`.tables.records.RegionRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.region</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.region</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.region</code> table reference
     */
    constructor(): this(DSL.name("region"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ru.itis.jooq.`_`.tables.records.RegionRecord>?, parentPath: InverseForeignKey<out Record, ru.itis.jooq.`_`.tables.records.RegionRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, REGION, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class RegionPath : Region, Path<ru.itis.jooq.`_`.tables.records.RegionRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ru.itis.jooq.`_`.tables.records.RegionRecord>?, parentPath: InverseForeignKey<out Record, ru.itis.jooq.`_`.tables.records.RegionRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<ru.itis.jooq.`_`.tables.records.RegionRecord>): super(alias, aliased)
        override fun `as`(alias: String): RegionPath = RegionPath(DSL.name(alias), this)
        override fun `as`(alias: Name): RegionPath = RegionPath(alias, this)
        override fun `as`(alias: Table<*>): RegionPath = RegionPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<ru.itis.jooq.`_`.tables.records.RegionRecord> = ru.itis.jooq.`_`.keys.REGION_PKEY

    private lateinit var _area: ru.itis.jooq.`_`.tables.Area.AreaPath

    /**
     * Get the implicit to-many join path to the <code>public.area</code> table
     */
    fun area(): ru.itis.jooq.`_`.tables.Area.AreaPath {
        if (!this::_area.isInitialized)
            _area = ru.itis.jooq.`_`.tables.Area.AreaPath(this, null, ru.itis.jooq.`_`.keys.AREA__AREA_REGION_CODE_FKEY.inverseKey)

        return _area;
    }

    val area: ru.itis.jooq.`_`.tables.Area.AreaPath
        get(): ru.itis.jooq.`_`.tables.Area.AreaPath = area()
    override fun `as`(alias: String): Region = Region(DSL.name(alias), this)
    override fun `as`(alias: Name): Region = Region(alias, this)
    override fun `as`(alias: Table<*>): Region = Region(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Region = Region(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Region = Region(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Region = Region(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Region = Region(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Region = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Region = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Region = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Region = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Region = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Region = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Region = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Region = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Region = where(DSL.notExists(select))
}
