/*
 * This file is generated by jOOQ.
 */
package ru.itis.jooq


import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.area</code>.
     */
    val AREA: ru.itis.jooq.`_`.tables.Area get() = ru.itis.jooq.`_`.tables.Area.AREA

    /**
     * The table <code>public.object</code>.
     */
    val OBJECT: ru.itis.jooq.`_`.tables.Object get() = ru.itis.jooq.`_`.tables.Object.OBJECT

    /**
     * The table <code>public.quarter</code>.
     */
    val QUARTER: ru.itis.jooq.`_`.tables.Quarter get() = ru.itis.jooq.`_`.tables.Quarter.QUARTER

    /**
     * The table <code>public.region</code>.
     */
    val REGION: ru.itis.jooq.`_`.tables.Region get() = ru.itis.jooq.`_`.tables.Region.REGION

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        ru.itis.jooq.`_`.tables.Area.AREA,
        ru.itis.jooq.`_`.tables.Object.OBJECT,
        ru.itis.jooq.`_`.tables.Quarter.QUARTER,
        ru.itis.jooq.`_`.tables.Region.REGION
    )
}
